name: Storm CMS Article
description: Storm CMS Article
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.article:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - article
