name: Storm CMS Article
description: Storm CMS Article
recipes:
  - core/recipes/editorial_workflow
  - storm_cms_content_type_base
  - storm_cms_person
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.article:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - article
